/* Generated by itemis CREATE code generator. */


#include "sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_Read_sensors(Statechart* handle);
static void enact_main_region_Process_received_values_UART(Statechart* handle);
static void enact_main_region_Send_data_UART___Process_values_OLED(Statechart* handle);
static void enact_main_region_Send_data_OLED(Statechart* handle);
static void enact_main_region_Title_screen(Statechart* handle);
static void exact_main_region_Process_received_values_UART(Statechart* handle);
static void exact_main_region_Send_data_UART___Process_values_OLED(Statechart* handle);
static void exact_main_region_Send_data_OLED(Statechart* handle);
static void exact_main_region_Title_screen(Statechart* handle);
static void enseq_main_region_Wait_for_timer_default(Statechart* handle);
static void enseq_main_region_Read_sensors_default(Statechart* handle);
static void enseq_main_region_Process_received_values_UART_default(Statechart* handle);
static void enseq_main_region_Send_data_UART___Process_values_OLED_default(Statechart* handle);
static void enseq_main_region_Send_data_OLED_default(Statechart* handle);
static void enseq_main_region_Title_screen_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_Wait_for_timer(Statechart* handle);
static void exseq_main_region_Read_sensors(Statechart* handle);
static void exseq_main_region_Process_received_values_UART(Statechart* handle);
static void exseq_main_region_Send_data_UART___Process_values_OLED(Statechart* handle);
static void exseq_main_region_Send_data_OLED(Statechart* handle);
static void exseq_main_region_Title_screen(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! The reactions of state Wait_for_timer. */
static sc_integer main_region_Wait_for_timer_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Read_sensors. */
static sc_integer main_region_Read_sensors_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Process_received_values_UART. */
static sc_integer main_region_Process_received_values_UART_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Send_data_UART / Process_values_OLED. */
static sc_integer main_region_Send_data_UART___Process_values_OLED_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Send_data_OLED. */
static sc_integer main_region_Send_data_OLED_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Title_screen. */
static sc_integer main_region_Title_screen_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_iterration_number(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_sample_no(handle, 0);
	statechart_internal_set_iterration_number(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_in_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_Wait_for_timer :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_WAIT_FOR_TIMER] == Statechart_main_region_Wait_for_timer
			);
				break;
		case Statechart_main_region_Read_sensors :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_READ_SENSORS] == Statechart_main_region_Read_sensors
			);
				break;
		case Statechart_main_region_Process_received_values_UART :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_PROCESS_RECEIVED_VALUES_UART] == Statechart_main_region_Process_received_values_UART
			);
				break;
		case Statechart_main_region_Send_data_UART___Process_values_OLED :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SEND_DATA_UART___PROCESS_VALUES_OLED] == Statechart_main_region_Send_data_UART___Process_values_OLED
			);
				break;
		case Statechart_main_region_Send_data_OLED :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SEND_DATA_OLED] == Statechart_main_region_Send_data_OLED
			);
				break;
		case Statechart_main_region_Title_screen :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_TITLE_SCREEN] == Statechart_main_region_Title_screen
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.timer_interrupt_raised = bool_false;
	handle->iface.i2c_callback_sensors_raised = bool_false;
	handle->iface.user_button_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Wait_for_timer :
		{
			main_region_Wait_for_timer_react(handle,-1);
			break;
		}
		case Statechart_main_region_Read_sensors :
		{
			main_region_Read_sensors_react(handle,-1);
			break;
		}
		case Statechart_main_region_Process_received_values_UART :
		{
			main_region_Process_received_values_UART_react(handle,-1);
			break;
		}
		case Statechart_main_region_Send_data_UART___Process_values_OLED :
		{
			main_region_Send_data_UART___Process_values_OLED_react(handle,-1);
			break;
		}
		case Statechart_main_region_Send_data_OLED :
		{
			main_region_Send_data_OLED_react(handle,-1);
			break;
		}
		case Statechart_main_region_Title_screen :
		{
			main_region_Title_screen_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			clear_in_events(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_timer_interrupt(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_timer_interrupt);
	run_cycle(handle);
}

void statechart_raise_i2c_callback_sensors(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_i2c_callback_sensors);
	run_cycle(handle);
}

void statechart_raise_user_button(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_user_button);
	run_cycle(handle);
}




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
{
	handle->internal.sample_no = value;
}
static void statechart_internal_set_iterration_number(Statechart* handle, sc_integer value)
{
	handle->internal.iterration_number = value;
}


/* implementations of all internal functions */

/* Entry action for state 'Read_sensors'. */
static void enact_main_region_Read_sensors(Statechart* handle)
{
	/* Entry action for state 'Read_sensors'. */
	statechart_read_i2c_sensors(handle);
}

static void enact_main_region_Process_received_values_UART(Statechart* handle)
{
	/* Entry action for state 'Process_received_values_UART'. */
	statechart_process_i2c_samples(handle,handle->internal.sample_no);
	handle->completed = bool_true;
}

static void enact_main_region_Send_data_UART___Process_values_OLED(Statechart* handle)
{
	/* Entry action for state 'Send_data_UART / Process_values_OLED'. */
	statechart_process_data_oled(handle,handle->internal.iterration_number);
	statechart_send_data_uart(handle);
	handle->internal.iterration_number++;
	handle->completed = bool_true;
}

static void enact_main_region_Send_data_OLED(Statechart* handle)
{
	/* Entry action for state 'Send_data_OLED'. */
	statechart_send_data_oled(handle);
	handle->completed = bool_true;
}

/* Entry action for state 'Title_screen'. */
static void enact_main_region_Title_screen(Statechart* handle)
{
	/* Entry action for state 'Title_screen'. */
	statechart_display_welcome_page(handle);
}

/* Exit action for state 'Process_received_values_UART'. */
static void exact_main_region_Process_received_values_UART(Statechart* handle)
{
	/* Exit action for state 'Process_received_values_UART'. */
	handle->internal.sample_no++;
}

/* Exit action for state 'Send_data_UART / Process_values_OLED'. */
static void exact_main_region_Send_data_UART___Process_values_OLED(Statechart* handle)
{
	/* Exit action for state 'Send_data_UART / Process_values_OLED'. */
	statechart_internal_set_sample_no(handle, 0);
}

/* Exit action for state 'Send_data_OLED'. */
static void exact_main_region_Send_data_OLED(Statechart* handle)
{
	/* Exit action for state 'Send_data_OLED'. */
	statechart_internal_set_iterration_number(handle, 0);
}

/* Exit action for state 'Title_screen'. */
static void exact_main_region_Title_screen(Statechart* handle)
{
	/* Exit action for state 'Title_screen'. */
	statechart_start_program(handle);
}

/* 'default' enter sequence for state Wait_for_timer */
static void enseq_main_region_Wait_for_timer_default(Statechart* handle)
{
	/* 'default' enter sequence for state Wait_for_timer */
	handle->stateConfVector[0] = Statechart_main_region_Wait_for_timer;
}

/* 'default' enter sequence for state Read_sensors */
static void enseq_main_region_Read_sensors_default(Statechart* handle)
{
	/* 'default' enter sequence for state Read_sensors */
	enact_main_region_Read_sensors(handle);
	handle->stateConfVector[0] = Statechart_main_region_Read_sensors;
}

/* 'default' enter sequence for state Process_received_values_UART */
static void enseq_main_region_Process_received_values_UART_default(Statechart* handle)
{
	/* 'default' enter sequence for state Process_received_values_UART */
	enact_main_region_Process_received_values_UART(handle);
	handle->stateConfVector[0] = Statechart_main_region_Process_received_values_UART;
}

/* 'default' enter sequence for state Send_data_UART / Process_values_OLED */
static void enseq_main_region_Send_data_UART___Process_values_OLED_default(Statechart* handle)
{
	/* 'default' enter sequence for state Send_data_UART / Process_values_OLED */
	enact_main_region_Send_data_UART___Process_values_OLED(handle);
	handle->stateConfVector[0] = Statechart_main_region_Send_data_UART___Process_values_OLED;
}

/* 'default' enter sequence for state Send_data_OLED */
static void enseq_main_region_Send_data_OLED_default(Statechart* handle)
{
	/* 'default' enter sequence for state Send_data_OLED */
	enact_main_region_Send_data_OLED(handle);
	handle->stateConfVector[0] = Statechart_main_region_Send_data_OLED;
}

/* 'default' enter sequence for state Title_screen */
static void enseq_main_region_Title_screen_default(Statechart* handle)
{
	/* 'default' enter sequence for state Title_screen */
	enact_main_region_Title_screen(handle);
	handle->stateConfVector[0] = Statechart_main_region_Title_screen;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Wait_for_timer */
static void exseq_main_region_Wait_for_timer(Statechart* handle)
{
	/* Default exit sequence for state Wait_for_timer */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Read_sensors */
static void exseq_main_region_Read_sensors(Statechart* handle)
{
	/* Default exit sequence for state Read_sensors */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Process_received_values_UART */
static void exseq_main_region_Process_received_values_UART(Statechart* handle)
{
	/* Default exit sequence for state Process_received_values_UART */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Process_received_values_UART(handle);
}

/* Default exit sequence for state Send_data_UART / Process_values_OLED */
static void exseq_main_region_Send_data_UART___Process_values_OLED(Statechart* handle)
{
	/* Default exit sequence for state Send_data_UART / Process_values_OLED */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Send_data_UART___Process_values_OLED(handle);
}

/* Default exit sequence for state Send_data_OLED */
static void exseq_main_region_Send_data_OLED(Statechart* handle)
{
	/* Default exit sequence for state Send_data_OLED */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Send_data_OLED(handle);
}

/* Default exit sequence for state Title_screen */
static void exseq_main_region_Title_screen(Statechart* handle)
{
	/* Default exit sequence for state Title_screen */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Title_screen(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Wait_for_timer :
		{
			exseq_main_region_Wait_for_timer(handle);
			break;
		}
		case Statechart_main_region_Read_sensors :
		{
			exseq_main_region_Read_sensors(handle);
			break;
		}
		case Statechart_main_region_Process_received_values_UART :
		{
			exseq_main_region_Process_received_values_UART(handle);
			break;
		}
		case Statechart_main_region_Send_data_UART___Process_values_OLED :
		{
			exseq_main_region_Send_data_UART___Process_values_OLED(handle);
			break;
		}
		case Statechart_main_region_Send_data_OLED :
		{
			exseq_main_region_Send_data_OLED(handle);
			break;
		}
		case Statechart_main_region_Title_screen :
		{
			exseq_main_region_Title_screen(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Title_screen_default(handle);
}


static sc_integer main_region_Wait_for_timer_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Wait_for_timer. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.timer_interrupt_raised == bool_true)
			{ 
				exseq_main_region_Wait_for_timer(handle);
				enseq_main_region_Read_sensors_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_Read_sensors_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Read_sensors. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.i2c_callback_sensors_raised == bool_true)
			{ 
				exseq_main_region_Read_sensors(handle);
				enseq_main_region_Process_received_values_UART_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_Process_received_values_UART_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Process_received_values_UART. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Process_received_values_UART */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_Process_received_values_UART(handle);
		/* The reactions of state null. */
		if ((handle->internal.sample_no) == (4))
		{ 
			enseq_main_region_Send_data_UART___Process_values_OLED_default(handle);
		}  else
		{
			if ((((handle->internal.iterration_number) == (9)) == bool_true) && (((handle->internal.sample_no) == (3)) == bool_true))
			{ 
				statechart_prepare_oled_screen(handle);
				enseq_main_region_Wait_for_timer_default(handle);
			}  else
			{
				enseq_main_region_Wait_for_timer_default(handle);
			}
		}
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_Send_data_UART___Process_values_OLED_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Send_data_UART / Process_values_OLED. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Send_data_UART / Process_values_OLED */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_Send_data_UART___Process_values_OLED(handle);
		/* The reactions of state null. */
		if ((handle->internal.iterration_number) == (10))
		{ 
			enseq_main_region_Send_data_OLED_default(handle);
		}  else
		{
			enseq_main_region_Wait_for_timer_default(handle);
		}
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_Send_data_OLED_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Send_data_OLED. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Send_data_OLED */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_Send_data_OLED(handle);
		/* 'default' enter sequence for state Wait_for_timer */
		handle->stateConfVector[0] = Statechart_main_region_Wait_for_timer;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_Title_screen_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Title_screen. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.user_button_raised == bool_true)
			{ 
				exseq_main_region_Title_screen(handle);
				enseq_main_region_Wait_for_timer_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_timer_interrupt:
		{
			handle->iface.timer_interrupt_raised = bool_true;
			return bool_true;
		}
		case Statechart_i2c_callback_sensors:
		{
			handle->iface.i2c_callback_sensors_raised = bool_true;
			return bool_true;
		}
		case Statechart_user_button:
		{
			handle->iface.user_button_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
