/* Generated by itemis CREATE code generator. */


#include "sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_orth_r1_screen(Statechart* handle);
static void enact_main_orth_r1_Read_I2C(Statechart* handle);
static void enact_main_orth_r1_Process_I2C(Statechart* handle);
static void enact_main_orth_r1_Send_uart(Statechart* handle);
static void enact_main_orth_r1_Oled(Statechart* handle);
static void enact_main_orth_r2_normal_mode(Statechart* handle);
static void enact_main_orth_r2_high_speed_mode(Statechart* handle);
static void enact_main_orth_r2_low_light_mode(Statechart* handle);
static void enact_main_welcome(Statechart* handle);
static void exact_main_orth_r1_screen(Statechart* handle);
static void exact_main_orth_r1_Process_I2C(Statechart* handle);
static void exact_main_orth_r1_Send_uart(Statechart* handle);
static void exact_main_orth_r2_normal_mode(Statechart* handle);
static void exact_main_orth_r2_high_speed_mode(Statechart* handle);
static void exact_main_orth_r2_low_light_mode(Statechart* handle);
static void enseq_main_orth_r1_screen_default(Statechart* handle);
static void enseq_main_orth_r1_Wait_for_timer_default(Statechart* handle);
static void enseq_main_orth_r1_Read_I2C_default(Statechart* handle);
static void enseq_main_orth_r1_Process_I2C_default(Statechart* handle);
static void enseq_main_orth_r1_Send_uart_default(Statechart* handle);
static void enseq_main_orth_r1_Oled_default(Statechart* handle);
static void enseq_main_orth_r2_normal_mode_default(Statechart* handle);
static void enseq_main_orth_r2_high_speed_mode_default(Statechart* handle);
static void enseq_main_orth_r2_low_light_mode_default(Statechart* handle);
static void enseq_main_welcome_default(Statechart* handle);
static void enseq_main_default(Statechart* handle);
static void exseq_main_orth_r1_screen(Statechart* handle);
static void exseq_main_orth_r1_Wait_for_timer(Statechart* handle);
static void exseq_main_orth_r1_Read_I2C(Statechart* handle);
static void exseq_main_orth_r1_Process_I2C(Statechart* handle);
static void exseq_main_orth_r1_Send_uart(Statechart* handle);
static void exseq_main_orth_r1_Oled(Statechart* handle);
static void exseq_main_orth_r2_normal_mode(Statechart* handle);
static void exseq_main_orth_r2_high_speed_mode(Statechart* handle);
static void exseq_main_orth_r2_low_light_mode(Statechart* handle);
static void exseq_main_welcome(Statechart* handle);
static void exseq_main(Statechart* handle);
static void react_main_orth_r1__choice_2(Statechart* handle);
static void react_main__entry_Default(Statechart* handle);
static void react_main__sync0(Statechart* handle);

/*! The reactions of state orth. */
static sc_integer main_orth_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state screen. */
static sc_integer main_orth_r1_screen_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Wait for timer. */
static sc_integer main_orth_r1_Wait_for_timer_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Read I2C. */
static sc_integer main_orth_r1_Read_I2C_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Process I2C. */
static sc_integer main_orth_r1_Process_I2C_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Send uart. */
static sc_integer main_orth_r1_Send_uart_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Oled. */
static sc_integer main_orth_r1_Oled_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state normal_mode. */
static sc_integer main_orth_r2_normal_mode_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state high_speed_mode. */
static sc_integer main_orth_r2_high_speed_mode_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state low_light_mode. */
static sc_integer main_orth_r2_low_light_mode_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state welcome. */
static sc_integer main_welcome_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_iterration_number(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_timer_required(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_timer_counter(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_mode_transition(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_set_auto_gain(handle, 0);
	statechart_set_required_sample_no(handle, 5);
	statechart_set_mode_type(handle, 0);
	statechart_internal_set_sample_no(handle, 0);
	statechart_internal_set_iterration_number(handle, 0);
	statechart_internal_set_timer_required(handle, 5);
	statechart_internal_set_timer_counter(handle, 0);
	statechart_internal_set_mode_transition(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_in_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVector[1] = Statechart_last_state;
	handle->stateConfVectorPosition = 1;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_orth :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH] >= Statechart_main_orth
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH] <= Statechart_main_orth_r2_low_light_mode);
				break;
		case Statechart_main_orth_r1_screen :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R1_SCREEN] == Statechart_main_orth_r1_screen
			);
				break;
		case Statechart_main_orth_r1_Wait_for_timer :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R1_WAIT_FOR_TIMER] == Statechart_main_orth_r1_Wait_for_timer
			);
				break;
		case Statechart_main_orth_r1_Read_I2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R1_READ_I2C] == Statechart_main_orth_r1_Read_I2C
			);
				break;
		case Statechart_main_orth_r1_Process_I2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R1_PROCESS_I2C] == Statechart_main_orth_r1_Process_I2C
			);
				break;
		case Statechart_main_orth_r1_Send_uart :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R1_SEND_UART] == Statechart_main_orth_r1_Send_uart
			);
				break;
		case Statechart_main_orth_r1_Oled :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R1_OLED] == Statechart_main_orth_r1_Oled
			);
				break;
		case Statechart_main_orth_r2_normal_mode :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R2_NORMAL_MODE] == Statechart_main_orth_r2_normal_mode
			);
				break;
		case Statechart_main_orth_r2_high_speed_mode :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R2_HIGH_SPEED_MODE] == Statechart_main_orth_r2_high_speed_mode
			);
				break;
		case Statechart_main_orth_r2_low_light_mode :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_ORTH_R2_LOW_LIGHT_MODE] == Statechart_main_orth_r2_low_light_mode
			);
				break;
		case Statechart_main_welcome :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_WELCOME] == Statechart_main_welcome
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.timer_interrupt_raised = bool_false;
	handle->iface.i2c_callback_sensors_raised = bool_false;
	handle->iface.user_button_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
 			sc_integer transitioned = -1;
	handle->stateConfVectorPosition = 0;
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_orth_r1_screen :
		{
			transitioned = main_orth_r1_screen_react(handle,transitioned);
			break;
		}
		case Statechart_main_orth_r1_Wait_for_timer :
		{
			transitioned = main_orth_r1_Wait_for_timer_react(handle,transitioned);
			break;
		}
		case Statechart_main_orth_r1_Read_I2C :
		{
			transitioned = main_orth_r1_Read_I2C_react(handle,transitioned);
			break;
		}
		case Statechart_main_orth_r1_Process_I2C :
		{
			transitioned = main_orth_r1_Process_I2C_react(handle,transitioned);
			break;
		}
		case Statechart_main_orth_r1_Send_uart :
		{
			transitioned = main_orth_r1_Send_uart_react(handle,transitioned);
			break;
		}
		case Statechart_main_orth_r1_Oled :
		{
			transitioned = main_orth_r1_Oled_react(handle,transitioned);
			break;
		}
		case Statechart_main_welcome :
		{
			transitioned = main_welcome_react(handle,transitioned);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	if ((handle->stateConfVectorPosition) < (1))
	{ 
		switch(handle->stateConfVector[ 1 ])
		{
			case Statechart_main_orth_r2_normal_mode :
			{
				main_orth_r2_normal_mode_react(handle,transitioned);
				break;
			}
			case Statechart_main_orth_r2_high_speed_mode :
			{
				main_orth_r2_high_speed_mode_react(handle,transitioned);
				break;
			}
			case Statechart_main_orth_r2_low_light_mode :
			{
				main_orth_r2_low_light_mode_react(handle,transitioned);
				break;
			}
			default: 
				/* do nothing */
				break;
		}
	} 
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			clear_in_events(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_timer_interrupt(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_timer_interrupt);
	run_cycle(handle);
}

void statechart_raise_i2c_callback_sensors(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_i2c_callback_sensors);
	run_cycle(handle);
}

void statechart_raise_user_button(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_user_button);
	run_cycle(handle);
}



sc_integer statechart_get_auto_gain(const Statechart* handle)
{
	return handle->iface.auto_gain;
}
void statechart_set_auto_gain(Statechart* handle, sc_integer value)
{
	handle->iface.auto_gain = value;
}
sc_integer statechart_get_required_sample_no(const Statechart* handle)
{
	return handle->iface.required_sample_no;
}
void statechart_set_required_sample_no(Statechart* handle, sc_integer value)
{
	handle->iface.required_sample_no = value;
}
sc_integer statechart_get_mode_type(const Statechart* handle)
{
	return handle->iface.mode_type;
}
void statechart_set_mode_type(Statechart* handle, sc_integer value)
{
	handle->iface.mode_type = value;
}

static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
{
	handle->internal.sample_no = value;
}
static void statechart_internal_set_iterration_number(Statechart* handle, sc_integer value)
{
	handle->internal.iterration_number = value;
}
static void statechart_internal_set_timer_required(Statechart* handle, sc_integer value)
{
	handle->internal.timer_required = value;
}
static void statechart_internal_set_timer_counter(Statechart* handle, sc_integer value)
{
	handle->internal.timer_counter = value;
}
static void statechart_internal_set_mode_transition(Statechart* handle, sc_integer value)
{
	handle->internal.mode_transition = value;
}


/* implementations of all internal functions */

/* Entry action for state 'screen'. */
static void enact_main_orth_r1_screen(Statechart* handle)
{
	/* Entry action for state 'screen'. */
	statechart_display_mode_type(handle,handle->iface.mode_type);
	statechart_change_timer_and_sensor(handle,handle->iface.mode_type);
	statechart_zero_data(handle);
}

/* Entry action for state 'Read I2C'. */
static void enact_main_orth_r1_Read_I2C(Statechart* handle)
{
	/* Entry action for state 'Read I2C'. */
	statechart_read_i2c_sensors(handle);
}

static void enact_main_orth_r1_Process_I2C(Statechart* handle)
{
	/* Entry action for state 'Process I2C'. */
	statechart_process_i2c_samples(handle,handle->internal.sample_no, handle->iface.mode_type);
	handle->completed = bool_true;
}

static void enact_main_orth_r1_Send_uart(Statechart* handle)
{
	/* Entry action for state 'Send uart'. */
	statechart_process_data_oled(handle,handle->iface.required_sample_no, handle->internal.iterration_number);
	statechart_send_data_uart(handle);
	handle->completed = bool_true;
}

static void enact_main_orth_r1_Oled(Statechart* handle)
{
	/* Entry action for state 'Oled'. */
	statechart_send_data_oled(handle);
	handle->completed = bool_true;
}

/* Entry action for state 'normal_mode'. */
static void enact_main_orth_r2_normal_mode(Statechart* handle)
{
	/* Entry action for state 'normal_mode'. */
	statechart_internal_set_timer_required(handle, 100);
	statechart_set_required_sample_no(handle, 5);
	statechart_set_auto_gain(handle, 1);
}

/* Entry action for state 'high_speed_mode'. */
static void enact_main_orth_r2_high_speed_mode(Statechart* handle)
{
	/* Entry action for state 'high_speed_mode'. */
	statechart_set_mode_type(handle, 1);
	statechart_internal_set_timer_required(handle, 160);
	statechart_set_required_sample_no(handle, 8);
	statechart_set_auto_gain(handle, 0);
}

/* Entry action for state 'low_light_mode'. */
static void enact_main_orth_r2_low_light_mode(Statechart* handle)
{
	/* Entry action for state 'low_light_mode'. */
	statechart_set_mode_type(handle, 2);
	statechart_internal_set_timer_required(handle, 40);
	statechart_set_required_sample_no(handle, 2);
}

/* Entry action for state 'welcome'. */
static void enact_main_welcome(Statechart* handle)
{
	/* Entry action for state 'welcome'. */
	statechart_display_welcome_page(handle);
}

/* Exit action for state 'screen'. */
static void exact_main_orth_r1_screen(Statechart* handle)
{
	/* Exit action for state 'screen'. */
	statechart_start_program(handle);
}

/* Exit action for state 'Process I2C'. */
static void exact_main_orth_r1_Process_I2C(Statechart* handle)
{
	/* Exit action for state 'Process I2C'. */
	handle->internal.sample_no++;
}

/* Exit action for state 'Send uart'. */
static void exact_main_orth_r1_Send_uart(Statechart* handle)
{
	/* Exit action for state 'Send uart'. */
	handle->internal.iterration_number++;
}

/* Exit action for state 'normal_mode'. */
static void exact_main_orth_r2_normal_mode(Statechart* handle)
{
	/* Exit action for state 'normal_mode'. */
	statechart_internal_set_mode_transition(handle, 1);
	statechart_set_mode_type(handle, 1);
}

/* Exit action for state 'high_speed_mode'. */
static void exact_main_orth_r2_high_speed_mode(Statechart* handle)
{
	/* Exit action for state 'high_speed_mode'. */
	statechart_internal_set_mode_transition(handle, 1);
	statechart_set_mode_type(handle, 2);
}

/* Exit action for state 'low_light_mode'. */
static void exact_main_orth_r2_low_light_mode(Statechart* handle)
{
	/* Exit action for state 'low_light_mode'. */
	statechart_internal_set_mode_transition(handle, 1);
	statechart_set_mode_type(handle, 0);
}

/* 'default' enter sequence for state screen */
static void enseq_main_orth_r1_screen_default(Statechart* handle)
{
	/* 'default' enter sequence for state screen */
	enact_main_orth_r1_screen(handle);
	handle->stateConfVector[0] = Statechart_main_orth_r1_screen;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Wait for timer */
static void enseq_main_orth_r1_Wait_for_timer_default(Statechart* handle)
{
	/* 'default' enter sequence for state Wait for timer */
	handle->stateConfVector[0] = Statechart_main_orth_r1_Wait_for_timer;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Read I2C */
static void enseq_main_orth_r1_Read_I2C_default(Statechart* handle)
{
	/* 'default' enter sequence for state Read I2C */
	enact_main_orth_r1_Read_I2C(handle);
	handle->stateConfVector[0] = Statechart_main_orth_r1_Read_I2C;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Process I2C */
static void enseq_main_orth_r1_Process_I2C_default(Statechart* handle)
{
	/* 'default' enter sequence for state Process I2C */
	enact_main_orth_r1_Process_I2C(handle);
	handle->stateConfVector[0] = Statechart_main_orth_r1_Process_I2C;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Send uart */
static void enseq_main_orth_r1_Send_uart_default(Statechart* handle)
{
	/* 'default' enter sequence for state Send uart */
	enact_main_orth_r1_Send_uart(handle);
	handle->stateConfVector[0] = Statechart_main_orth_r1_Send_uart;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Oled */
static void enseq_main_orth_r1_Oled_default(Statechart* handle)
{
	/* 'default' enter sequence for state Oled */
	enact_main_orth_r1_Oled(handle);
	handle->stateConfVector[0] = Statechart_main_orth_r1_Oled;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state normal_mode */
static void enseq_main_orth_r2_normal_mode_default(Statechart* handle)
{
	/* 'default' enter sequence for state normal_mode */
	enact_main_orth_r2_normal_mode(handle);
	handle->stateConfVector[1] = Statechart_main_orth_r2_normal_mode;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state high_speed_mode */
static void enseq_main_orth_r2_high_speed_mode_default(Statechart* handle)
{
	/* 'default' enter sequence for state high_speed_mode */
	enact_main_orth_r2_high_speed_mode(handle);
	handle->stateConfVector[1] = Statechart_main_orth_r2_high_speed_mode;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state low_light_mode */
static void enseq_main_orth_r2_low_light_mode_default(Statechart* handle)
{
	/* 'default' enter sequence for state low_light_mode */
	enact_main_orth_r2_low_light_mode(handle);
	handle->stateConfVector[1] = Statechart_main_orth_r2_low_light_mode;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state welcome */
static void enseq_main_welcome_default(Statechart* handle)
{
	/* 'default' enter sequence for state welcome */
	enact_main_welcome(handle);
	handle->stateConfVector[0] = Statechart_main_welcome;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main */
static void enseq_main_default(Statechart* handle)
{
	/* 'default' enter sequence for region main */
	react_main__entry_Default(handle);
}

/* Default exit sequence for state screen */
static void exseq_main_orth_r1_screen(Statechart* handle)
{
	/* Default exit sequence for state screen */
	handle->stateConfVector[0] = Statechart_main_orth;
	handle->stateConfVectorPosition = 0;
	exact_main_orth_r1_screen(handle);
}

/* Default exit sequence for state Wait for timer */
static void exseq_main_orth_r1_Wait_for_timer(Statechart* handle)
{
	/* Default exit sequence for state Wait for timer */
	handle->stateConfVector[0] = Statechart_main_orth;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state Read I2C */
static void exseq_main_orth_r1_Read_I2C(Statechart* handle)
{
	/* Default exit sequence for state Read I2C */
	handle->stateConfVector[0] = Statechart_main_orth;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state Process I2C */
static void exseq_main_orth_r1_Process_I2C(Statechart* handle)
{
	/* Default exit sequence for state Process I2C */
	handle->stateConfVector[0] = Statechart_main_orth;
	handle->stateConfVectorPosition = 0;
	exact_main_orth_r1_Process_I2C(handle);
}

/* Default exit sequence for state Send uart */
static void exseq_main_orth_r1_Send_uart(Statechart* handle)
{
	/* Default exit sequence for state Send uart */
	handle->stateConfVector[0] = Statechart_main_orth;
	handle->stateConfVectorPosition = 0;
	exact_main_orth_r1_Send_uart(handle);
}

/* Default exit sequence for state Oled */
static void exseq_main_orth_r1_Oled(Statechart* handle)
{
	/* Default exit sequence for state Oled */
	handle->stateConfVector[0] = Statechart_main_orth;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state normal_mode */
static void exseq_main_orth_r2_normal_mode(Statechart* handle)
{
	/* Default exit sequence for state normal_mode */
	handle->stateConfVector[1] = Statechart_main_orth;
	handle->stateConfVectorPosition = 1;
	exact_main_orth_r2_normal_mode(handle);
}

/* Default exit sequence for state high_speed_mode */
static void exseq_main_orth_r2_high_speed_mode(Statechart* handle)
{
	/* Default exit sequence for state high_speed_mode */
	handle->stateConfVector[1] = Statechart_main_orth;
	handle->stateConfVectorPosition = 1;
	exact_main_orth_r2_high_speed_mode(handle);
}

/* Default exit sequence for state low_light_mode */
static void exseq_main_orth_r2_low_light_mode(Statechart* handle)
{
	/* Default exit sequence for state low_light_mode */
	handle->stateConfVector[1] = Statechart_main_orth;
	handle->stateConfVectorPosition = 1;
	exact_main_orth_r2_low_light_mode(handle);
}

/* Default exit sequence for state welcome */
static void exseq_main_welcome(Statechart* handle)
{
	/* Default exit sequence for state welcome */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main */
static void exseq_main(Statechart* handle)
{
	/* Default exit sequence for region main */
	/* Handle exit of all possible states (of Statechart.main) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_orth_r1_screen :
		{
			exseq_main_orth_r1_screen(handle);
			break;
		}
		case Statechart_main_orth_r1_Wait_for_timer :
		{
			exseq_main_orth_r1_Wait_for_timer(handle);
			break;
		}
		case Statechart_main_orth_r1_Read_I2C :
		{
			exseq_main_orth_r1_Read_I2C(handle);
			break;
		}
		case Statechart_main_orth_r1_Process_I2C :
		{
			exseq_main_orth_r1_Process_I2C(handle);
			break;
		}
		case Statechart_main_orth_r1_Send_uart :
		{
			exseq_main_orth_r1_Send_uart(handle);
			break;
		}
		case Statechart_main_orth_r1_Oled :
		{
			exseq_main_orth_r1_Oled(handle);
			break;
		}
		case Statechart_main_welcome :
		{
			exseq_main_welcome(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Handle exit of all possible states (of Statechart.main) at position 1... */
	switch(handle->stateConfVector[ 1 ])
	{
		case Statechart_main_orth_r2_normal_mode :
		{
			exseq_main_orth_r2_normal_mode(handle);
			break;
		}
		case Statechart_main_orth_r2_high_speed_mode :
		{
			exseq_main_orth_r2_high_speed_mode(handle);
			break;
		}
		case Statechart_main_orth_r2_low_light_mode :
		{
			exseq_main_orth_r2_low_light_mode(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* The reactions of state null. */
static void react_main_orth_r1__choice_2(Statechart* handle)
{
	/* The reactions of state null. */
	if ((handle->internal.mode_transition) == (1))
	{ 
		statechart_internal_set_mode_transition(handle, 0);
		statechart_internal_set_sample_no(handle, 0);
		statechart_internal_set_iterration_number(handle, 0);
		enseq_main_orth_r1_screen_default(handle);
	}  else
	{
		enseq_main_orth_r1_Read_I2C_default(handle);
	}
}

/* Default react sequence for initial entry  */
static void react_main__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_welcome_default(handle);
}

/* The reactions of state null. */
static void react_main__sync0(Statechart* handle)
{
	/* The reactions of state null. */
	enseq_main_orth_r1_screen_default(handle);
	enseq_main_orth_r2_normal_mode_default(handle);
}


static sc_integer main_orth_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state orth. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	} return transitioned_after;
}

static sc_integer main_orth_r1_screen_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state screen. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if ((handle->internal.timer_counter) == (handle->internal.timer_required))
			{ 
				exseq_main_orth_r1_screen(handle);
				statechart_internal_set_timer_counter(handle, 0);
				enseq_main_orth_r1_Wait_for_timer_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			if (handle->iface.timer_interrupt_raised == bool_true)
			{ 
				handle->internal.timer_counter++;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_orth_r1_Wait_for_timer_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Wait for timer. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.timer_interrupt_raised == bool_true)
			{ 
				exseq_main_orth_r1_Wait_for_timer(handle);
				react_main_orth_r1__choice_2(handle);
				transitioned_after = 0;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_orth_r1_Read_I2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Read I2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.i2c_callback_sensors_raised == bool_true)
			{ 
				exseq_main_orth_r1_Read_I2C(handle);
				enseq_main_orth_r1_Process_I2C_default(handle);
				transitioned_after = 0;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_orth_r1_Process_I2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Process I2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Process I2C */
		handle->stateConfVector[0] = Statechart_main_orth;
		handle->stateConfVectorPosition = 0;
		exact_main_orth_r1_Process_I2C(handle);
		/* The reactions of state null. */
		if ((handle->internal.sample_no) == (handle->iface.required_sample_no))
		{ 
			statechart_internal_set_sample_no(handle, 0);
			enseq_main_orth_r1_Send_uart_default(handle);
		}  else
		{
			if ((((handle->internal.iterration_number) == (9)) == bool_true) && (((handle->internal.sample_no) == ((handle->iface.required_sample_no - 1))) == bool_true))
			{ 
				statechart_prepare_oled_screen(handle);
				enseq_main_orth_r1_Wait_for_timer_default(handle);
			}  else
			{
				enseq_main_orth_r1_Wait_for_timer_default(handle);
			}
		}
	} 
	return transitioned_after;
}

static sc_integer main_orth_r1_Send_uart_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Send uart. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Send uart */
		handle->stateConfVector[0] = Statechart_main_orth;
		handle->stateConfVectorPosition = 0;
		exact_main_orth_r1_Send_uart(handle);
		/* The reactions of state null. */
		if ((handle->internal.iterration_number) == (10))
		{ 
			statechart_internal_set_iterration_number(handle, 0);
			enseq_main_orth_r1_Oled_default(handle);
		}  else
		{
			enseq_main_orth_r1_Wait_for_timer_default(handle);
		}
	} 
	return transitioned_after;
}

static sc_integer main_orth_r1_Oled_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Oled. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Oled */
		handle->stateConfVector[0] = Statechart_main_orth;
		handle->stateConfVectorPosition = 0;
		/* 'default' enter sequence for state Wait for timer */
		handle->stateConfVector[0] = Statechart_main_orth_r1_Wait_for_timer;
		handle->stateConfVectorPosition = 0;
	} 
	return transitioned_after;
}

static sc_integer main_orth_r2_normal_mode_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state normal_mode. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (1))
		{ 
			if (handle->iface.user_button_raised == bool_true)
			{ 
				exseq_main_orth_r2_normal_mode(handle);
				enseq_main_orth_r2_high_speed_mode_default(handle);
				main_orth_react(handle,0);
				transitioned_after = 1;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_orth_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_orth_r2_high_speed_mode_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state high_speed_mode. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (1))
		{ 
			if (handle->iface.user_button_raised == bool_true)
			{ 
				exseq_main_orth_r2_high_speed_mode(handle);
				enseq_main_orth_r2_low_light_mode_default(handle);
				main_orth_react(handle,0);
				transitioned_after = 1;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_orth_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_orth_r2_low_light_mode_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state low_light_mode. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (1))
		{ 
			if (handle->iface.user_button_raised == bool_true)
			{ 
				exseq_main_orth_r2_low_light_mode(handle);
				enseq_main_orth_r2_normal_mode_default(handle);
				main_orth_react(handle,0);
				transitioned_after = 1;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_orth_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_welcome_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state welcome. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.user_button_raised == bool_true)
			{ 
				exseq_main_welcome(handle);
				react_main__sync0(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_timer_interrupt:
		{
			handle->iface.timer_interrupt_raised = bool_true;
			return bool_true;
		}
		case Statechart_i2c_callback_sensors:
		{
			handle->iface.i2c_callback_sensors_raised = bool_true;
			return bool_true;
		}
		case Statechart_user_button:
		{
			handle->iface.user_button_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
