/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechart_read_I2C_Sensors
- statechart_check_min_max_pc
- statechart_save_average_data
- statechart_send_data_uart
- statechart_check_min_max_oled
- statechart_send_data_oled
- statechart_zero_pc_data
- statechart_zero_oled_data
- statechart_save_i2c_samples
- statechart_save_data_oled
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/
extern void statechart_read_I2C_Sensors( Statechart* handle);
extern void statechart_check_min_max_pc( Statechart* handle);
extern void statechart_save_average_data( Statechart* handle);
extern void statechart_send_data_uart( Statechart* handle);
extern void statechart_check_min_max_oled( Statechart* handle);
extern void statechart_send_data_oled( Statechart* handle);
extern void statechart_zero_pc_data( Statechart* handle);
extern void statechart_zero_oled_data( Statechart* handle);
extern void statechart_save_i2c_samples( Statechart* handle, const sc_integer sample_no);
extern void statechart_save_data_oled( Statechart* handle, const sc_integer iterration_number);





#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
