/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartIface interface scope.
*/
typedef struct StatechartIface StatechartIface;

/*!
* Forward declaration of the data structure for the StatechartInternal interface scope.
*/
typedef struct StatechartInternal StatechartInternal;

#ifdef __cplusplus
}
#endif

#include "sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file
Header of the state machine 'Statechart'.
*/

#ifndef STATECHART_EVENTQUEUE_BUFFERSIZE
#define STATECHART_EVENTQUEUE_BUFFERSIZE 20
#endif
#ifndef STATECHART_IN_EVENTQUEUE_BUFFERSIZE
#define STATECHART_IN_EVENTQUEUE_BUFFERSIZE STATECHART_EVENTQUEUE_BUFFERSIZE
#endif
#ifndef SC_INVALID_EVENT_VALUE
#define SC_INVALID_EVENT_VALUE 0
#endif
/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 11

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 2

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R1_DISPLAY_MODE_TYPE 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R1_WAIT_FOR_TIMER 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R1_READ_I2C_SENSORS 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R1_PROCESS_I2C_SAMPLES 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R1_SEND_DATA_UART 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R1_SEND_DATA_OLED 0
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R2_REGULAR_MODE 1
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R2_HIGH_SPEED_MODE 1
#define SCVI_STATECHART_MAIN_MAIN_PROGRAM_R2_LOW_LIGHT_MODE 1
#define SCVI_STATECHART_MAIN_WELCOME_PAGE 0


/* 
 * Enum of event names in the statechart.
 */
typedef enum  {
	Statechart_invalid_event = SC_INVALID_EVENT_VALUE,
	Statechart_timer_interrupt,
	Statechart_i2c_callback_sensors,
	Statechart_user_button
} StatechartEventID;

/*
 * Struct that represents a single event.
 */
typedef struct {
	StatechartEventID name;
} statechart_event;

/*
 * Queue that holds the raised events.
 */
typedef struct statechart_eventqueue_s {
	statechart_event *events;
	sc_integer capacity;
	sc_integer pop_index;
	sc_integer push_index;
	sc_integer size;
} statechart_eventqueue;

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	Statechart_main_Main_program,
	Statechart_main_Main_program_r1_Display_mode_type,
	Statechart_main_Main_program_r1_Wait_for_timer,
	Statechart_main_Main_program_r1_Read_I2C_sensors,
	Statechart_main_Main_program_r1_Process_I2C_samples,
	Statechart_main_Main_program_r1_Send_data_UART,
	Statechart_main_Main_program_r1_Send_data_OLED,
	Statechart_main_Main_program_r2_Regular_mode,
	Statechart_main_Main_program_r2_High_speed_mode,
	Statechart_main_Main_program_r2_Low_light_mode,
	Statechart_main_Welcome_page
} StatechartStates;


/*! Type declaration of the data structure for the StatechartIface interface scope. */
struct StatechartIface
{
	sc_boolean timer_interrupt_raised;
	sc_boolean i2c_callback_sensors_raised;
	sc_boolean user_button_raised;
};



/*! Type declaration of the data structure for the StatechartInternal interface scope. */
struct StatechartInternal
{
	sc_integer mode_type;
	sc_integer transition_flag;
	sc_integer mode_transition;
	sc_integer required_sample_no;
	sc_integer sample_no;
	sc_integer iterration_number;
	sc_integer timer_required;
	sc_integer timer_counter;
	sc_integer frames_before;
};






/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartIface iface;
	StatechartInternal internal;
	sc_boolean completed;
	sc_boolean doCompletion;
	sc_boolean isExecuting;
	sc_integer stateConfVectorPosition;
	statechart_eventqueue in_event_queue;
	statechart_event in_buffer[STATECHART_IN_EVENTQUEUE_BUFFERSIZE];
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);

/*! 
Can be used by the client code to trigger a run to completion step without raising an event.
*/
extern void statechart_trigger_without_event(Statechart* handle);



/*! Raises the in event 'timer_interrupt' that is defined in the default interface scope. */ 
extern void statechart_raise_timer_interrupt(Statechart* handle);
/*! Raises the in event 'i2c_callback_sensors' that is defined in the default interface scope. */ 
extern void statechart_raise_i2c_callback_sensors(Statechart* handle);
/*! Raises the in event 'user_button' that is defined in the default interface scope. */ 
extern void statechart_raise_user_button(Statechart* handle);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
